# These are supported funding model platforms

github: #[puppeteer-screen-recorder]
patreon: # Replace with a single Patreon username
open_collective: puppeteer-screen-recorder
custom: ["https://paypal.me/prasanaworld"]
